name: demo_ican
description: demo for i can help project


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^1.3.1
  http: ^0.12.0+4
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.2
  syncfusion_flutter_charts: ^17.4.46
  youtube_player_flutter: ^6.0.3+2
  webview_flutter: ^0.3.19+6
  datetime_picker_formfield: ^1.0.0
  carousel_slider: ^1.4.1
  flutter_staggered_grid_view: ^0.3.0
  image_picker: ^0.6.3+1
  bubble: ^1.1.9+1
  intl: ^0.16.0
  progress_dialog: ^1.2.0
  google_fonts: ^0.3.8
  charts_flutter: ^0.8.1
  fl_animated_linechart: ^1.0.2
  flutter_local_notifications: ^1.1.6
  fluttertoast: ^3.1.3
  connectivity: ^0.4.6+2
  #bloc
  flutter_bloc: ^3.2.0
  equatable: ^1.0.0
  meta: ^1.1.6

  #firebase
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.1.1
  rxdart: ^0.23.0
  firebase_analytics: ^5.0.2
  firebase_storage: ^3.1.1
  firestore_ui: ^1.7.2
  firebase_messaging: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/language/en-US.json
    - assets/language/ar-DZ.json
    - assets/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
