name: demo_ican
description: demo for i can help project


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^1.3.1
  http: ^0.12.0+4
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.2

  #bloc
  flutter_bloc: ^3.2.0
  equatable: ^1.0.0
  meta: ^1.1.6

  #firebase
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.1.1
  rxdart: ^0.23.0
  firebase_analytics: ^5.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
    - assets/language/en-US.json
    - assets/language/ar-DZ.json
    - assets/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
